//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyKTAppWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTENT
    {
        public int CONTENT_ID { get; set; }
        public Nullable<int> TEAM_ID { get; set; }
        public string CONTENT_TYPE { get; set; }
        public string CONTENT_DESCRIPTION { get; set; }
        public string CONTENT_DOCUMENTS { get; set; }
        public string UPDATED_BY { get; set; }
    
        public virtual CONTENT CONTENT1 { get; set; }
        public virtual CONTENT CONTENT2 { get; set; }
    }
}
