//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyKTAppWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEAM
    {
        public int TEAM_ID { get; set; }
        public string TEAM_FULL_NAME { get; set; }
        public string TEAM_ABBREVIATED_NAME { get; set; }
        public string TEAM_LOGO_PATH { get; set; }
        public string TEAM_DESCRIPTION { get; set; }
    }
}
